language: python
jobs:
  include:
  - name: Python 3.8
    python: 3.8
  - name: Python 3.7
    python: 3.7
before_install:
- python --version
- pip install -U pip
install:
- pip install -r requirements.txt -r requirements_test.txt
script:
- PYTHONPATH=`pwd` pytest -rpP --log-level info tests/test_smile.py --cov='.'
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: tIN5NHlNYXQfAi/2OkS5GaiG1tj5DqaG6xT2uiUZX0QKgncpvLIspcVMMQh26tOXq94/iShizmikXFJdEXDNISrv33Piwqs7XSdkHrcc55AoTqww6lZaUfNafgfe2ITh61hOBMlTZ914hAnhYKNxrNUrRLnX6el0dcWVJ62AJHGCCr49fq6tZz85yC+OP0C7BBJCuV4n7OqNlrKsZS4TF8Q/t3uUcwKpVzZWZwB8q7TRLv7S1NSGMAkKIKEXE5avIMHV8I/O2GieQAFHtX2yTcj1xyGAVBJPG9hK3M4prU4ifDtftPfWQF3rOKM77jdUWRNkH1f8JEkB0hJiMt01HEBV+f0vslEKXuKhodU1xjVfr0QCCXCxZEbhPCEG5IPTKVWMB33cVmR6SIA6f05oR3N48IiD7paQgmdxQX5o/saHAXf/GmnikHMP4CBxWg+3ArMtYaX6Nz5Ndoikn8ti3iXcJW0WRU4Fdhz3Qzn7WMTaf5WkMPk3cWxK6BJIcS5OH3Gb8bMKyVrD2/xtBHDEIMAc5ulQYlBv14lICMxkGYCCFAIq09uvKws5Oz37LjknpGc+3mrmvBtYa8AJ56y1ZB6/ndJh0H231EtJRuICBfEUcKTlawJKz5CcJRXIfT2dh6u8XdLIggFiX9wqH8kLVTd0VgbPVAawIGouR2/LXsg=
  on:
    branch: main
  skip_existing: true
