language: python
jobs:
  include:
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.8"
      python: 3.8
before_install:
- python --version
- pip install -U pip
install:
- pip install -r requirements.txt -r tests/requirements.txt
script: 
- PYTHONPATH=`pwd` pytest -rpP --log-level info tests/test_smile.py --cov='.'
#- PYTHONPATH=`pwd` flake8 --config=.flake8 plugwise/*.py tests/*py
#- PYTHONPATH=`pwd` pydocstyle plugwise/*.py tests/*py
#- PYTHONPATH=`pwd` pylint --rcfile=pylintrc plugwise/*.py
after_success:
- codecov
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: STugFJQydP2cD9f5cIF8tXabQLjuThD7jdlUDA6T6R0yqHa8rdre8ZwGpZSbpn2qHFNyZP91NKttlfmdz+nWNNIvQbBG4ZSMDVTKFbF2U/bt/LXVZUPl5ig51ywImWXugy5PR3c4RSPJLXAORJLDDkULqBeHPbVk61IY3G1Im28wYzjQOi9c6VtaMiMNzFJdcxvoA0Z/olT27whocADpdMl4QexR6qXenM/7FhEMi7JQQ5mFMGdlkujS3/oIm4h2AHvBZomvd36XWLfzdqoMelaybeLcs9oYIlH2FyFotA+zdopYdQSjmXqUdFEiXuodZ5UO7/meP9ary3A3KgwNoT0eGeDXB9YCurBY1YZ0vZ8skfkf2BfumMUujKhJkj+lcWbjimAl+55t+5L0D3Ri9Ug4f3F1BfdYbVfIWw+XJm24G4TIlPwpq+/pAhsqYdXJFRgw4GfhUpHk4J16jOflV+qB1c8Kx73rzaMNfbUtSbdBVlNrTWaiw9OOxKSRmzQ4qqSq1bx/XvKy82rJm8wqhhUmqZECc5W69UmJPdk4i/4qnXe9xjmX3REp0CGNY6kd57H+SfSXuWmNe3Y3jOIydcYZrDY0BBgEOGHVKKgdfXSIGFZd0UtI20dfQMj0ZESTjIj1BCr8LdxriW/iAn29LvEwS/t32gRvTVnT3Q0erhY=
  on:
    branch: master
  skip_existing: true
